version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "repetition-numbers"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-195rj4614lsr"
s3_prefix = "repetition-numbers"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
